### ISSUE TITLE
rationale for the `interpret` function name

### ISSUE THREAD

**Issue by nsajko** [jakobjpeters/PAQ.jl#8]
Usually, in other CAS software, this is called *evaluate* or *substitute* in my experience. Is there a rationale for choosing *interpret* instead?

**Comment by nsajko** [comment]
https://en.wikipedia.org/wiki/Interpretation_(logic)

**Comment by jakobjpeters** [comment]
Hi! Thank you for the issue.

You correctly identified my rationale. This function was developed early on as I was implementing the truth tables, and I discovered it was easy to support partial interpretation as well. However, you can still substitute non-truth values and I agree that another name would be more fitting. `interpret` is currently a light wrapper over `map`, but I don't yet support generalized substitution.

`evaluate` is currently used to define the semantics of an operator. For example, `evaluate(::typeof(→), p, q) = ¬p ∨ q`. So, I intend to replace this function with `substitute` or something similar once I have a more generalized implementation.
